### ISSUE TITLE
check_ncpa.py -M processes gives : An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR') 

### ISSUE THREAD

**Issue by bzazzera** [NagiosEnterprises/ncpa#599] opened 2019-12-16 14:32 UTC
Hi all,
When I run this command : /usr/local/nagios/libexec/check_ncpa.py -H x.x.x.x -t 'mytoken' -M processes under Debian 10.2 it gives the following error : UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')
Same error with python 2.7.16 and 3.7.3
After some research I discovered that this problem comes from the french version of my Windows 2016 Server that send accented characters.

It seems that check_ncpa.py python program works fine with utf8 coded characters but not in latin-1.
Could anyone confirm that point ?
 Thanks. Bruno

**Comment by jomann09** [comment] 2019-12-17 16:46
The issue with this is related to the other issues that have to with languages. The problem isn't with check_ncpa.py it's with the actual agent itself. I've made some changes in the past to try to get it to work better but when there are utf8 characters in output from the processes command it will end up dying. You can see this here also #439

**Comment by jomann09** [comment] 2020-02-20 19:58
Going to close this as a duplicate, the utf8 character issues should be resolved in NCPA 3

**Closed by jomann09** 2020-02-20 19:58 UTC

**Comment by lirfernandes** [comment] 2022-08-11 16:42
Hi @jomann09 any idea of when the ncpa 3 will be released?
we continue having many check with this error, and no update on ncpa has been release.
for example:
![image](https://user-images.githubusercontent.com/111076722/184187749-b3b859b3-8a78-49f8-bb13-263e54c9e372.png)
