### ISSUE TITLE
NCPA client not working for services on newer Debian releases

### ISSUE THREAD

**Issue by oneoffdallas** [NagiosEnterprises/ncpa#255] opened 2016-08-03 16:23 UTC
You can't call services via the standard API calls on newer Debian releases. Until there is a fix, I have created a quick workaround for this. Simply create a file called service_check.sh and drop the script (between the dashes below) into your /usr/local/ncpa/plugins directory. The service call then looks like the following. Hope this helps! -- Dallas

check_xi_ncpa_agent!-t '<pass>' -P <port> -M 'agent/plugin/service_check.sh/<service name>'

---
#!/bin/bash

service="$1"

running=$( /etc/init.d/$service status 2>/dev/null | grep 'Active: active' | wc -l )

if [ $running -gt 0 ]
then
        echo "OK - $service running"
        exit 0
else
        echo "WARNING - $service not running"
        exit 3
fi

**Comment by jomann09** [comment] 2016-08-03 16:26
Thanks for posting the workaround - I am going to test this on 2.0.0 since there were some service changes, however it seems like it might actually be a bigger problem on Debian. I'll update this when I get a chance!

**Comment by jomann09** [comment] 2016-08-08 00:53
Having confirmed that this works in 2.0.0 I am going to close this!

**Closed by jomann09** 2016-08-08 00:53 UTC
Labels: Bug

**Comment by oneoffdallas** [comment] 2016-08-08 13:46
Excellent! If you create a deb 2.0 package I can test it for you. Thanks!

**Comment by jomann09** [comment] 2016-08-08 14:14
I will get back to you on this, I can probably get one out today.

**Comment by jomann09** [comment] 2016-08-08 15:46
There should now be a .deb in https://assets.nagios.com/downloads/ncpa/dev/ and I haven't tested it yet... this *should* work on Debian 8, if it doesn't ... we will have to setup a new build, which isn't really a problem, but we didn't need to before!
