### ISSUE TITLE
NCPA 2.1.1 Could not find platform independent libraries [Consider setting $PYTHONHOME]

### ISSUE THREAD

**Issue by pilot513** [NagiosEnterprises/ncpa#424] opened 2018-01-18 17:04 UTC
Hello.
I'm try check with NCPA plugin check_tomcat.py (on ncpa v.2.0.6 worked fine)
When check (active & passive modes) i get error:

`check_ncpa.py -H 192.168.10.1 -t 'Secter' -P 5693 -M 'plugins/check_tomcat.py' -q 'args=-H localhost,args=-p 8080,args=-u nagiosmon,args=-a Passw0rd,args=-m mem,args=-w 85,args=-c 94' -D -v`

`Traceback (most recent call last):
  File "/usr/lib64/nagios/plugins/check_ncpa.py", line 10, in <module>
    import ssl
  File "/usr/lib64/python2.7/ssl.py", line 94, in <module>
    from collections import namedtuple
  File "/usr/lib64/python2.7/collections.py", line 8, in <module>
    from _collections import deque, defaultdict
ImportError: No module named _collections`

With settings:
echo $PYTHONPATH $PYTHONHOME
/usr/lib64/python2.7 /usr/bin/python
on Nagios host 

Without:
`File returned contained:
{
    "returncode": 1,
    "stdout": "Could not find platform independent libraries <prefix>\nCould not find platform dependent libraries <exec_prefix>\nConsider setting $PYTHONHOME to <prefix>[:<exec_prefix>]\nImportError: No module named site"
}
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site`

What can be done ?

**Comment by jomann09** [comment] 2018-01-18 17:08
You can edit your `ncpa_listener` and `ncpa_passive` script in your `/etc/init.d/` folder and remove or comment out the lines that export the `LD_LIBRARY_PATH` at the top - which is what is causing these issues. There should be a fix for 2.1.2 but it shouldn't cause any problems for your NCPA system unless you're running on SLES.

**Comment by pilot513** [comment] 2018-01-18 17:08
In passive mode, ncps_passive return:
`Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site`

Check by:
`%HOSTNAME%|Tomcat.SrvMem|180 = plugins/check_tomcat.py?args=-H localhost?args=-p 8080?args=-u nagiosmon?args=-a Passw0rd?args=-m mem?args=-w 85?args=-c 94`

**Comment by pilot513** [comment] 2018-01-18 17:09
No. Server/Clients running on RHEL/OEL 7.x

**Comment by pilot513** [comment] 2018-01-18 17:11
In /etc/init.d/ncpa_listener:
`19 # Source function library
     20 if [ -f /etc/rc.d/init.d/functions ]; then
     21     . /etc/rc.d/init.d/functions
     22 fi
     23
     24 BASEDIR="/usr/local/ncpa"
     25 export LD_LIBRARY_PATH=$BASEDIR:$PATH
     26
`
What should I change?

**Comment by jomann09** [comment] 2018-01-18 17:14
Remove line 25 in the example you gave

**Comment by pilot513** [comment] 2018-01-18 17:15
already :)
Worked:
# /usr/lib64/nagios/plugins/check_ncpa.py -H 192.168.10.1 -t 'Secret' -P 5693 -M 'plugins/check_tomcat.py' -q 'args=-H localhost,args=-p 8080,args=-u nagiosmon,args=-a Passw0rd,args=-m mem,args=-w 85,args=-c 94' -D -v
Connecting to: https://192.168.10.1:5693/api/plugins/check_tomcat.py/?token=Secret&check=1&args=-H+localhost&args=-p+8080&args=-u+nagiosmon&args=-a+Passw0rd&args=-m+mem&args=-w+85&args=-c+94
File returned contained:
{
    "returncode": 0,
    "stdout": "OK Used memory 875.9 MB of 3.56 GB(24.06%)|'Used_memory'=24%;85;94"
}
OK Used memory 875.9 MB of 3.56 GB(24.06%)|'Used_memory'=24%;85;94

**Comment by pilot513** [comment] 2018-01-18 17:23
I want to ask another question

How to set parameters in passive mode for check_mysql_health ?

In active mode worked:
./check_ncpa.py -H 192.168.10.100 -t 'ewTmNgf4pbtBVjuD9VU8' -P 5693 -M 'plugins/check_mysql_health' -a ' -H localhost --username nagiosmon --password Passw0rd --mode sql --name SELECT%20round%28%28%28data_length%20%2B%20index_length%29%20%2F%201024%20%2F%201024%29%2C%202%29%20%60Size%20in%20MB%60%20FROM%20information_schema.TABLES%20WHERE%20table_schema%20%3D%20%22CUST%22%20AND%20table_name%20%3D%20%22%7BTDServicesCharge%7D%22 --name2 BlockUnblock --warning 15000.000000 --critical 18000.000000'

OK - blockunblock: 2387.470000 | 'blockunblock'=2387.470000;15000.000000;18000.000000

In passive not:
%HOSTNAME%|SQL.Size.CUST.EntityPropertyValue|120 = plugins/check_mysql_health/-H/localhost/--username/nagiosmon/--password/Passw0rd/--mode/sql/--name/"SELECT%20round%28%28%28data_length%20%2B%20index_length%29%20%2F%201024%20%2F%201024%29%2C%202%29%20%60Size%20in%20MB%60%20FROM%20information_schema.TABLES%20WHERE%20table_schema%20%3D%20%22CUST%22%20AND%20table_name%20%3D%20%22EntityPropertyValue%22/--name2/BlockUnblock/--warning/15000.000000/--critical/18000.000000

Version 2.0.5

**Comment by jomann09** [comment] 2018-01-28 04:59
I can't seem to get this to work properly in my system (the issue I mean) but have you tried changing the passive check to not have the encoded values?

**Comment by jomann09** [comment] 2018-01-28 05:40
I'm going to close this because the main issue is a duplicate of #417 if you'd like more help with this issue I'd suggest posting in the general forums on support.nagios.com or open a clean issue here so I can look at it once again.

**Closed by jomann09** 2018-01-28 05:40 UTC
Labels: Question
