### ISSUE TITLE
Question on sources list removal

### ISSUE THREAD

**Issue by timcanty** [NagiosEnterprises/ncpa#1024] opened 2023-11-16 12:37 UTC
Hi, Just noticed that we are now getting errors on our ubuntu hosts that we up to now NCPA was installed via apt get and an entry in the sources.list, have noticed now version 3 has been released we are getting "No public key", and the instructions to install this way have now been removed from the website.

Is this no longer supported installing that way? or is this temporary. Would be interested to know the reason behind the change?

Kind Regards

**Comment by ne-bbahn** [comment] 2023-11-30 17:55
Hello, we have updated our GPG key and this is likely causing your issue. You can update your nagios repo using the information in the [README.rst](https://github.com/NagiosEnterprises/ncpa/blob/master/README.rst) of this repo or from [repo.nagios.com](repo.nagios.com).

**Comment by ne-bbahn** [comment] 2023-12-06 16:55
If this is not the issue, please respond here. Otherwise I will close this issue in 1 week from today. You will still be able to respond and I can reopen it at that time if the issue is not solved.

**Closed** 2023-12-06 17:05 UTC
Labels: 3.X.X, close pending
