### ISSUE TITLE
Issue running checks simultaneously on one (Windows)host

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#219] opened 2016-05-03 09:23 UTC
Hi!

Rescheduling or executing more checks simultaneously on one (Windows) host is causing ncpa returning an unknown state with message:

`
UNKNOWN: Error occurred while running the plugin. Use the verbose flag for more details.
`

When starting the checks with flag -v the plugin output is:

`
An error occurred:[Errno 104] Connection reset by peer
`

Can someone confirm this issue?

Best regards,

ccztux

**Comment by ccztux** [comment] 2016-05-03 12:40
I have tested it running a powershell script plugin which average runtime is about 8 seconds, but sometimes it also happens with the default api checks (e.g. cpu, virtual memory...). This issue occures on various systems.

**Comment by jhomann** [comment] 2016-05-10 05:36
How many checks are running against the host?

**Comment by ccztux** [comment] 2016-05-10 08:54
For testing purposes i have installed ncpa on my desktop machine (Windows 7 Enterprise 64 bit). There are no nagios checks implemented on that client.

Powershell test script:
`
Start-Sleep -s 8
Write-Host "Done..."
`

When i execute this plugin via ncpa two times nearly at the same time the error occurs. The issue seems to be in check_ncpa.py, because when i try this with curl, the issue doesnt occur.

**Comment by ccztux** [comment] 2016-05-10 10:16
This is the verbose output (flags -v -s) in case of this issue:

`
Connecting to: https://myhost:5693/api/agent/plugin/test.ps1/?token=mytoken&check=1
The stack trace:Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_ncpa.py", line 266, in main
    info_json = get_json(options)
  File "/usr/local/nagios/libexec/check_ncpa.py", line 220, in get_json
    filename, _ = urlretrieve(url)
  File "/usr/lib64/python2.6/urllib.py", line 93, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib64/python2.6/urllib.py", line 267, in retrieve
    block = fp.read(bs)
  File "/usr/lib64/python2.6/socket.py", line 383, in read
    data = self._sock.recv(left)
  File "/usr/lib64/python2.6/ssl.py", line 215, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.6/ssl.py", line 136, in read
    return self._sslobj.read(len)
error: [Errno 104] Connection reset by peer
`

**Comment by ccztux** [comment] 2016-05-12 06:54
Can you please try to reproduce it on your system?

Powershell test script:
```
Start-Sleep -s 5
Write-Host "Done..."
```


Simulation script of nagios checks:
```
#!/bin/bash

/usr/local/nagios/libexec/check_ncpa.py -H your_ip -T 60 -t your_token -M /agent/plugin/test.ps1 -s -v &
sleep 1
/usr/local/nagios/libexec/check_ncpa.py -H your_ip -T 60 -t your_token -M /agent/plugin/test.ps1 -s -v &
sleep 1
/usr/local/nagios/libexec/check_ncpa.py -H your_ip -T 60 -t your_token -M /agent/plugin/test.ps1 -s -v &
sleep 1
/usr/local/nagios/libexec/check_ncpa.py -H your_ip -T 60 -t your_token -M /agent/plugin/test.ps1 -s -v &
sleep 1
/usr/local/nagios/libexec/check_ncpa.py -H your_ip -T 60 -t your_token -M /agent/plugin/test.ps1 -s -v &
sleep 1
/usr/local/nagios/libexec/check_ncpa.py -H your_ip -T 60 -t your_token -M /agent/plugin/test.ps1 -s -v &
sleep 1
```


We have multiple nagios sytems with many ncpa agents installed and on these systems the test situation produces following issue and that regardless of the fact, that in the test-script there is a sleep interval of 1 second between the checks:
```
[user@localhost ~]$ ./ncpa_test.sh
Connecting to: https://my_ip:5693/api/agent/plugin/test.ps1/?token=my_token&check=1
Connecting to: https://my_ip:5693/api/agent/plugin/test.ps1/?token=my_token&check=1
Connecting to: https://my_ip:5693/api/agent/plugin/test.ps1/?token=my_token&check=1
Connecting to: https://my_ip:5693/api/agent/plugin/test.ps1/?token=my_token&check=1
Connecting to: https://my_ip:5693/api/agent/plugin/test.ps1/?token=my_token&check=1
Connecting to: https://my_ip:5693/api/agent/plugin/test.ps1/?token=my_token&check=1
[user@localhost ~]$ File returned contained:
{
  "value": {
    "returncode": 0,
    "stdout": "Done..."
  }
}
Done...
The stack trace:Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_ncpa.py", line 266, in main
    info_json = get_json(options)
  File "/usr/local/nagios/libexec/check_ncpa.py", line 220, in get_json
    filename, _ = urlretrieve(url)
  File "/usr/lib64/python2.6/urllib.py", line 93, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib64/python2.6/urllib.py", line 267, in retrieve
    block = fp.read(bs)
  File "/usr/lib64/python2.6/socket.py", line 383, in read
    data = self._sock.recv(left)
  File "/usr/lib64/python2.6/ssl.py", line 215, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.6/ssl.py", line 136, in read
    return self._sslobj.read(len)
error: [Errno 104] Connection reset by peer

The stack trace:Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_ncpa.py", line 266, in main
    info_json = get_json(options)
  File "/usr/local/nagios/libexec/check_ncpa.py", line 220, in get_json
    filename, _ = urlretrieve(url)
  File "/usr/lib64/python2.6/urllib.py", line 93, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib64/python2.6/urllib.py", line 267, in retrieve
    block = fp.read(bs)
  File "/usr/lib64/python2.6/socket.py", line 383, in read
    data = self._sock.recv(left)
  File "/usr/lib64/python2.6/ssl.py", line 215, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.6/ssl.py", line 136, in read
    return self._sslobj.read(len)
error: [Errno 104] Connection reset by peer

The stack trace:Traceback (most recent call last):
  File "/usr/local/nagios/libexec/check_ncpa.py", line 266, in main
    info_json = get_json(options)
  File "/usr/local/nagios/libexec/check_ncpa.py", line 220, in get_json
    filename, _ = urlretrieve(url)
  File "/usr/lib64/python2.6/urllib.py", line 93, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib64/python2.6/urllib.py", line 267, in retrieve
    block = fp.read(bs)
  File "/usr/lib64/python2.6/socket.py", line 383, in read
    data = self._sock.recv(left)
  File "/usr/lib64/python2.6/ssl.py", line 215, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.6/ssl.py", line 136, in read
    return self._sslobj.read(len)
error: [Errno 104] Connection reset by peer

File returned contained:
{
  "value": {
    "returncode": 0,
    "stdout": "Done..."
  }
}
Done...
File returned contained:
{
  "value": {
    "returncode": 0,
    "stdout": "Done..."
  }
}
Done...
```

We suppose that the issue is caused by urllib in check_ncpa.py.

**Comment by jhomann** [comment] 2016-05-12 07:53
Oh I'm really sorry! I thought I had sent a reply! I will definitely test this out in my dev environment and see if I can't come up with some information and possibly a fix for this!

**Comment by ccztux** [comment] 2016-05-12 08:14
This sounds great! Thank you!

**Comment by jhomann** [comment] 2016-05-14 07:31
I can confirm this only seems to be an issue with the check_ncpa.py plugin and not the actual agent itself. From the API it seems it can do multiple at once without any issues.

**Comment by jhomann** [comment] 2016-05-14 09:54
This should be fixed with the 1.0.0 version of check_ncpa.py (the one in master) you can copy it out of the repo here and test it out if you'd like. I did some testing and seems okay using urllib2.urlopen instead of the old version.

**Comment by ccztux** [comment] 2016-05-14 10:20
Cool, thanks! I will test it as far as i can and give you a reply. I think that will be on Tuesday.

**Comment by jhomann** [comment] 2016-05-15 08:36
Thanks! I'm going to close this for now since my testing shows that it should be fixed. Let me know if you have any issues with it.

**Closed by jhomann** 2016-05-15 08:36 UTC
Labels: bug
