### ISSUE TITLE
service check gives '500 INTERNAL SERVER ERROR' when using match=regexec

### ISSUE THREAD

**Issue by MrPippin66** [NagiosEnterprises/ncpa#679] opened 2020-09-03 15:34 UTC
NCPA = ncpa-2.2.2-1.el7.x86_64
OS = Red Hat Enterprise Linux Server release 7.8 (Maipo)

When using check_ncpa.py to check a service using "match=regex", I'm getting a '500 INTERNAL SERVER ERROR'

Example:

# /usr/local/nagios/libexec/check_ncpa.py -H SERVER  -t TOKEN -M 'services' -q 'service=sshd,status=running,match=regex'
UNKNOWN: An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')

Service I'm trying to match for:

# /usr/local/nagios/libexec/check_ncpa.py -H SERVER  -t TOKEN -M 'services' --list | grep sshd
        "centrify-sshd": "running",

**Comment by ccztux** [comment] 2020-09-03 17:35
This seems to be a duplicate of #626

**Comment by jomann09** [comment] 2020-09-03 18:27
I'm closing this as duplicate, will get this fixed for 2.3.0

**Closed by jomann09** 2020-09-03 18:27 UTC
Labels: Bug, Duplicate
