### ISSUE TITLE
Upgrade to ncpa 2.0.4 on rhel6 stops upstart services

### ISSUE THREAD

**Issue by jvandermeulen** [NagiosEnterprises/ncpa#355] opened 2017-06-26 19:29 UTC
An update from NCPA 2.0.3 to 2.0.4 on RHEL6 finishes with errors leaving NCPA in a defective state. 
Apparently NCPA 2.0.4 requires glibc-2.14 but the install requirements in the .SPEC file do not list them `rpm -q ncpa --requires`

> Starting NCPA Listener: /usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/ncpa_listener)
/usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/libpython2.7.so.1.0)
[FAILED]
Starting NCPA Passive:  /usr/local/ncpa/ncpa_passive: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/ncpa_passive)
/usr/local/ncpa/ncpa_passive: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/libpython2.7.so.1.0)
[FAILED]
Stopping NCPA Listener: /usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/ncpa_listener)
/usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/libpython2.7.so.1.0)
[FAILED]
Stopping NCPA Passive:  /usr/local/ncpa/ncpa_passive: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/ncpa_passive)
/usr/local/ncpa/ncpa_passive: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/libpython2.7.so.1.0)
[FAILED]
  Cleanup    : ncpa-2.0.3-1.el6.x86_64                                                                                                                                                   2/2
warning:    erase unlink of /usr/local/ncpa/ncpa.key failed: No such file or directory
warning:    erase unlink of /usr/local/ncpa/ncpa.crt failed: No such file or directory
  Verifying  : ncpa-2.0.4-1.el7.centos.x86_64                                                                                                                                            1/2
  Verifying  : ncpa-2.0.3-1.el6.x86_64 

After package installation/upgrade the services won't start.
The files ncpa.key en ncpa.crt are wiped.

> [root@rhel6-ncpa ncpa.cfg.d]# service ncpa_listener status
> /usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/ncpa_listener)
> /usr/local/ncpa/ncpa_listener: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/ncpa/libpython2.7.so.1.0)

This error occurs on the latest rhel6 version: Red Hat Enterprise Linux Server release 6.8 (Santiago)

**Comment by jomann09** [comment] 2017-06-26 19:35
It was built on the same CentOS 6 systems as before, can you check what version your glibc is so that I can compare?

**Comment by jomann09** [comment] 2017-06-26 19:35
Oh wait a minute why is it trying to install a el7 package?

**Comment by jvandermeulen** [comment] 2017-06-26 20:35
You're right Jake, my bad. This el6 system had nagios-repo-7-2.el7.noarch.rpm installed. 
I restored my previous snapshot, made sure the proper nagios repo was attached and performed an upgrade once again. This time no issues with regards to libraries or certificates or private keys. 
However both ncpa_listener and ncpa_passive are in a stopped state after upgrade. Please note the starting/stopping order below....

> Running Transaction
  Updating   : ncpa-2.0.4-1.el6.x86_64                                                                                                                                                   1/2
warning: /usr/local/ncpa/etc/ncpa.cfg created as /usr/local/ncpa/etc/ncpa.cfg.rpmnew
Starting NCPA Listener: [  OK  ]
Starting NCPA Passive:  [  OK  ]
Stopping NCPA Listener: [  OK  ]
Stopping NCPA Passive:  [  OK  ]
  Cleanup    : ncpa-2.0.3-1.el6.x86_64                                                                                                                                                   2/2
  Verifying  : ncpa-2.0.4-1.el6.x86_64                                                                                                                                                   1/2
  Verifying  : ncpa-2.0.3-1.el6.x86_64                                                                                                                                                   2/2
Updated:
  ncpa.x86_64 0:2.0.4-1.el6

I will rename this issue so it reflects the services issue

**Comment by jomann09** [comment] 2017-06-27 13:18
This is a duplicate of #329 and #356 so am going to close it, the stopping issue will no longer happen after the next upgrade!

**Closed by jomann09** 2017-06-27 13:18 UTC
