### ISSUE TITLE
ncpa for windows connection reset by peer

### ISSUE THREAD

**Issue by pierluigiconti** [NagiosEnterprises/ncpa#346] opened 2017-05-25 11:07 UTC
Hello,
we're using NCPA for windows version 2.0.3  (and also tested the 2.0.4 one), and we're having a connection reset by peer issue.

Here you are with a stack trace of the error:

```
The stack trace:Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/contrib/check_ncpa.py", line 282, in main
    info_json = get_json(options)
  File "/usr/lib/nagios/plugins/contrib/check_ncpa.py", line 233, in get_json
    ret = ''.join(ret)
  File "/usr/lib/python2.7/socket.py", line 530, in next
    line = self.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 602, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
error: [Errno 104] Connection reset by peer
```

To reproduce this issue and to exclude nagios server you can run the check_ncpa.py twice with a for loop, something like this

```
while true; do /usr/lib/nagios/plugins/contrib/check_ncpa.py  -H xxx -t 'xxx' -M 'plugins/alldsk2.ps1/-s1 500 -w1 50 -c1 100 ' -D ; done 
```

If you run this loop only one time you will not have any error.
If you run this loop concurrently (twice or more) you'll have the issue.

**Comment by jomann09** [comment] 2017-05-25 14:39
I'll look at this more, but I believe this is due to the internal server that we use in NCPA (it's not a production web server) but I can look into seeing if there are some things we can tweak that'll let it handle a high volume of checks coming in.

**Comment by pierluigiconti** [comment] 2017-05-26 07:30
Ok,
thank you jomann.

As you said that you are not using a production web server, about NCPA, we would like to use it in our production because is very interesting, can we rely this project is stable for production?

Thank you a lot,

**Comment by jomann09** [comment] 2017-05-26 14:23
When I say it doesn't use a production web server I mean that the daemon that is NCPA accepts HTTPS requests to an internal web server - not something like apache, lighttpd, or nginx. It shouldn't be an issue in production, many people use it in production. That doesn't mean we can't make it better. The type of web server it uses internally is not fully featured like the ones mentioned is all. You couldn't, for instance, host a website on the web server that is bundled in NCPA.

**Comment by pierluigiconti** [comment] 2017-05-26 14:33
Ok, sure, I only used this thread just to be sure that ncpa is the right replacement for nrpe and nsclient in our environment.
I've used a (ugly) workaround for our Windows's agent, I just reduced the max_concurrent_checks in my nagios.cfg so I will not have concurrent checks on the same host.

Thank you,

**Comment by jomann09** [comment] 2017-05-26 14:47
Not a problem, I will look into it. From what I can tell, this looks like it might be an issue with how the plugin does the checks and not on the agent side of things. I'll look into it in-depth and get back to you.

**Comment by jomann09** [comment] 2017-07-22 05:01
So what I think is going on here is that the plugins are being ran through subprocess and then are actually waiting for the process to come back before returning. I am not sure if we will be able to fix this right away due to the fact that I am assuming that the problem is the running of a plugin blocking the python... I think I will have to look into fixing this in NCPA 3 when we start doing some multiprocessing/threading that will hopefully solve some of the weird issues with it locking up.

**Comment by pierluigiconti** [comment] 2017-07-24 07:25
Do you mean the execution of plugins via nagios?
In that case that's not exact, because, we simulated the issue, executing just two single processes running single check each.
So it just seem due to the windows agent's webserver (as you said), infact, I haven't the same issues running linux boxes.

Thank you

**Comment by jomann09** [comment] 2017-08-25 21:10
I'm adding this to 2.1 but may have to wait until 3. I am working on 2.1 right now so I would do some testing on this and see if it's possible to fix earlier.

**Comment by pierluigiconti** [comment] 2017-08-28 07:29
ok, thank you, I'll wait for it

**Comment by jomann09** [comment] 2017-12-05 14:32
I can't get this to actually happen on my systems, although I have not tested it as extensively as I will during the re-writing of the way it runs plugins. I'm going to move this to 3 though, since 2.1 is coming out soon and this won't be able to be fixed in that one.

**Comment by jomann09** [comment] 2019-10-22 15:06
This is a duplicate of #532 even though it came later, it should be the same problem. The next release should fix this.

**Closed by jomann09** 2019-10-22 15:06 UTC
Labels: Bug, Duplicate
