### ISSUE TITLE
NCPA Agent Services stuck in "Starting State" after rebooting

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#99] opened 2014-11-24 17:44 UTC
This is happening on a Windows Server 2008 r2 64bit and Windows Server 2012 64 bit.

ncpa 1.7.2

These servers get rebooted after patching once a month.  Last month I thought it a fluke and moved on.  However, patching as this past Friday night, and once again, the NCPA Services are both stuck in a "Starting state"

I have to manually kill the processes in and start the services to correct this.

We are still in testing but very close to a production rollout.

I cannot rollout this agent if this going to keep happening.

Any assistance is greatly appreciated.

**Comment by scot0357** [comment] 2015-01-12 06:24
Add @varnar fix in https://github.com/NagiosEnterprises/ncpa/pull/123. Tested on my own servers, verified that this fix does indeed put the service in Delayed Start, however, I could not reproduce the original issue. Closing this as it will be included in 1.8.

**Closed by scot0357** 2015-01-12 06:24 UTC
Labels: bug
