### ISSUE TITLE
RHEL 6 NCPA service check fails via api on few services 2.1.1

### ISSUE THREAD

**Issue by manas3** [NagiosEnterprises/ncpa#427] opened 2018-01-23 09:07 UTC
Hey,

We have recently updated NCPA on clients 2.0.6 -> 2.1.1 but after upgrading the service check is failing only on few services while on other service on same host seems to be working.

Can you check on a bug or something which is causing this?

**Service not working:**

```
/usr/local/nagios/libexec/check_ncpa.py -H testmachine -t 'XXXX' -P 5693 -M 'services' -q 'service=rh-mysql56-mysqld,state=running' -v
Connecting to: https://testmachine:5693/api/services/?token=XXXX&check=1&service=rh-mysql56-mysqld&state=running
File returned contained:
{
    "returncode": 2, 
    "stdout": "CRITICAL: rh-mysql56-mysqld is stopped (should be running)"
}
CRITICAL: rh-mysql56-mysqld is stopped (should be running)
```

**Service working:**

```
 /usr/local/nagios/libexec/check_ncpa.py -H testmachine -t 'XXXX' -P 5693 -M 'services' -q 'service=sshd,state=running' -v
Connecting to: https://testmachine:5693/api/services/?token=XXXX&check=1&service=sshd&state=running
File returned contained:
{
    "returncode": 0, 
    "stdout": "OK: sshd is running"
}
OK: sshd is running
```

**Comment by nagiosllc** [comment] 2018-01-23 20:25
Hello Manas3,

 

Are you certain that mysqld is running on the host?

 

Brian Olson

Pre-Sales Technical Support Specialist

Nagios Enterprises, LLC

The Industry Standard in Network Infrastructure Monitoring 

 <http://www.nagios.com/> www.nagios.com

**Comment by manas3** [comment] 2018-01-24 06:39
Hey Brian,

Yes I am certain, the service is running, so does other services. I was checking the stopped services ncpa is reporting and their actual status on the server they seem to be running.

Also I tried to dig deeper and it looks like some permission issue, where the nagios user don't have necessary permission to check the status.

I was looking at the services.py, may be running the in sudo mode would solve this?

https://github.com/NagiosEnterprises/ncpa/blob/caa4b472fe0f313305231dcf540237f28701a938/agent/listener/services.py#L191

Thanks,
Manas

**Comment by jomann09** [comment] 2018-01-24 16:37
You can actually run the whole daemon as a specific user (like root) which shouldn't really have any negative security implications - we used to always run it as root but it's just safer to have it drop down to nagios instead. You can change the user it runs as in `ncpa.cfg` file for the `[listener]` section to see if the nagios user isn't allowed to check the status of that service. The way we can get service data in most other OS doesn't seem to have this issue so it's really an EL6 thing.

**Comment by manas3** [comment] 2018-01-25 06:48
Yes, I am aware of that. But its a big security measure for us to run as root. For nagios user we have sudo rules placed the commands, plugins, etc it needs to run.

A ncpa check through plug works like a charm as we can use sudo for nagios user. But for services api nagios user can't rally have privileges.

Is there anything we can try to get it work? Except using plugins

Thanks

**Comment by jomann09** [comment] 2018-01-25 12:39
Without using a separate plugin and adding it to the sudo plugins no, not at this time. Besides changing the main user to use root.

**Comment by manas3** [comment] 2018-01-25 12:52
Ok that's a bit disappointing, using root user is not an option for us due to security implications

**Comment by jvandermeulen** [comment] 2018-01-25 22:46
@manas3 I was unable to reproduce this error on EL6 running rh-mysql56-mysql-server-5.6.34-2.el6.x86_64 initially using NCPA 2.0.4 later on upgraded to NCPA 2.1.1

What is the output of `su - nagios -c "service rh-mysql56-mysqld status"`?

**Comment by jomann09** [comment] 2018-01-28 03:36
I will probably close this soon if we don't get a response, although I am assuming that you'll end up choosing a workaround. I have not been able to come up with a good way to get status information any better for EL6, so this is just what we have. If anyone has any suggestions, please let me know. The sudo route is no-go though because that would require changing sudo configurations and whatnot, which I don't think our agent should do.

**Comment by manas3** [comment] 2018-01-29 07:33
I was able to give read permission for nagios user to read the needed files to check the status. So somehow got it to working.

But still it fails for other few services due to lack or perms, however strangely this doesn't occur in ncpa version 2.0.6 on the same configuration. If it helps..

Also on security front, running a command with sudo rather running the agent with sudo is lot less secure and is not a possible option for us.

Thanks,
Manas

**Comment by jomann09** [comment] 2018-01-29 12:39
The reason it works differently than 2.0.x is because those versions were doing a `ps aux` and grepping for processes with the name that we were looking for. It allowed us to bypass some security checks on init scripts but it also was highly inaccurate.

**Comment by jomann09** [comment] 2018-02-01 20:02
Thanks for the input! I'm going to cancel this and continue to think about it in the future, in non EL6 systems this shouldn't be an issue ... so this will only be an issue for a few more years :)

**Closed by jomann09** 2018-02-01 20:02 UTC
Labels: Question, Won't Fix
