### ISSUE TITLE
NCPA always shows the status of postgresql as "stopped"

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/ncpa#142] opened 2015-02-04 16:47 UTC
NCPA always shows the status of postgresql as "stopped" even though the service is running:
```
service postgresql status
postmaster (pid  1286) is running...
```
However, when I access the API, I see:
```
{
  "value": {
    "services": {
      ... 
      "postgresql": "stopped", 
      ...
    }
  }
}
```

**Comment by varnar** [comment] 2015-02-05 08:00
Dear developers - confirmed:
[Thu Feb 05 01:54:56] root@sq5vplngs001:/usr/local/nagios/libexec# /etc/init.d/postgresql status
postmaster (pid  31363) is running...


"postgresql": "stopped", 

Looks like you trying to find running process

**Comment by krobertson71** [comment] 2015-02-05 16:41
Mine read the same way in Linux, but report accurately on Windows servers.  I think it's the way something gets installed on a Linux server as to whether or not it registers as a service properly.  This also happens with other software as well.  I have a Numara Asset Core agent running, but when I check the /service/ its is listed as Stopped even thought the process is runnning and functioning normally.

This is why I just check for running processes on Linux.

**Comment by krobertson71** [comment] 2015-02-05 16:54
Windows example.. shows properly

"NCPA Listener ncpalistener": "running", 

Linux example .. shows incorrectly even those other OS level services are correct:

ncpa_listener": "stopped" (We know is running as I pulled this from the NCPA API.
"crond": "running", (We know this to be true as it is a system level service).

So not sure if the problem is with NCPA or the OS and the way it is reporting it to NCPA.  I lean toward the latter.

**Comment by vAndrewJ** [comment] 2015-02-17 21:31
I'm seeing the same with crushftp daemon.

**Comment by jm-welch** [comment] 2015-04-15 17:29
More discussion around this topic also present in #137

**Comment by jhomann** [comment] 2016-05-11 04:10
Can anyone give me an example of a service that is now working on Windows? I have yet to find one in the new build of 2.0.0 with psutil 4.1.0 ... I'll be checking Linux next for some of the common ones you all have found to see if the updated psutil helps.

**Comment by tmcnag** [comment] 2016-05-11 14:00
not* working I believe you mean  :)

**Comment by jhomann** [comment] 2016-05-11 14:01
Yes, thank you! An example of one that is not working for anyone :)

**Comment by jhomann** [comment] 2016-05-16 06:11
Closing this as duplicate right now. Use #137

**Closed by jhomann** 2016-05-16 06:11 UTC
Labels: bug
