### ISSUE TITLE
AIX build fails

### ISSUE THREAD

**Issue by ahmedaijaz1** [NagiosEnterprises/ncpa#541] opened 2019-05-31 10:12 UTC
AIX NCPA agent build fails on an AIX-7.2 system

$ oslevel -r
7200-00

I don't see any build instructions for AIX. 
Also fulfilling the requirements for require.txt fails with errors:

pip install -r resources/require.txt --upgrade
Requirement already up-to-date: psutil in /opt/dxc/python/lib/python2.7/site-packages (from -r resources/require.txt (line 1)) (5.6.2)
Requirement already up-to-date: requests in /opt/dxc/python/lib/python2.7/site-packages (from -r resources/require.txt (line 2)) (2.22.0)
Requirement already up-to-date: Jinja2 in /opt/dxc/python/lib/python2.7/site-packages (from -r resources/require.txt (line 3)) (2.10.1)
Requirement already up-to-date: flask==0.10.1 in /opt/dxc/python/lib/python2.7/site-packages (from -r resources/require.txt (line 4)) (0.10.1)
Requirement already up-to-date: werkzeug in /opt/dxc/python/lib/python2.7/site-packages (from -r resources/require.txt (line 5)) (0.15.4)
Requirement already up-to-date: docutils in /opt/dxc/python/lib/python2.7/site-packages (from -r resources/require.txt (line 6)) (0.14)
Collecting pyOpenSSL (from -r resources/require.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl
Collecting cryptography (from -r resources/require.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/c2/95/f43d02315f4ec074219c6e3124a87eba1d2d12196c2767fadfdc07a83884/cryptography-2.7.tar.gz
  Installing build dependencies ... error
  ERROR: Complete output from command /opt/dxc/python/bin/python2.7 /opt/dxc/python/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-OuvkVZ/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; python_implementation != '"'"'PyPy'"'"'':
  DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
  Collecting setuptools>=40.6.0
    Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
  Collecting cffi!=1.11.3,>=1.8
    Using cached https://files.pythonhosted.org/packages/93/1a/ab8c62b5838722f29f3daffcc8d4bd61844aa9b5f437341cc890ceee483b/cffi-1.12.3.tar.gz
  Collecting pycparser (from cffi!=1.11.3,>=1.8)
  Installing collected packages: setuptools, wheel, pycparser, cffi
    Running setup.py install for cffi: started
      Running setup.py install for cffi: finished with status 'error'
      ERROR: Complete output from command /opt/dxc/python/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-e5yONc/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-Yv2tgt/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-OuvkVZ/overlay --compile:
      ERROR: _configtest.c:1: error: thread-local storage not supported for this target
      Note: will not use '__thread' in the C code
      ***** The above error message can be safely ignored.

      running install
      running build
      running build_py
      creating build
      creating build/lib.aix-7.2-2.7
      creating build/lib.aix-7.2-2.7/cffi
      copying cffi/__init__.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/api.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/backend_ctypes.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/cffi_opcode.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/commontypes.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/cparser.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/error.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/ffiplatform.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/lock.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/model.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/pkgconfig.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/recompiler.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/setuptools_ext.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/vengine_cpy.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/vengine_gen.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/verifier.py -> build/lib.aix-7.2-2.7/cffi
      copying cffi/_cffi_include.h -> build/lib.aix-7.2-2.7/cffi
      copying cffi/parse_c_type.h -> build/lib.aix-7.2-2.7/cffi
      copying cffi/_embedding.h -> build/lib.aix-7.2-2.7/cffi
      copying cffi/_cffi_errors.h -> build/lib.aix-7.2-2.7/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.aix-7.2-2.7
      creating build/temp.aix-7.2-2.7/c
      gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/opt/dxc/python/include/python2.7 -c c/_cffi_backend.c -o build/temp.aix-7.2-2.7/c/_cffi_backend.o
      /opt/dxc/python/lib/python2.7/config/ld_so_aix gcc -pthread -bI:/opt/dxc/python/lib/python2.7/config/python.exp build/temp.aix-7.2-2.7/c/_cffi_backend.o -lffi -o build/lib.aix-7.2-2.7/_cffi_backend.so
      collect2: library libffi not found
      error: command '/opt/dxc/python/lib/python2.7/config/ld_so_aix' failed with exit status 1
      ----------------------------------------
  ERROR: Command "/opt/dxc/python/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-e5yONc/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-Yv2tgt/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-OuvkVZ/overlay --compile" failed with error code 1 in /tmp/pip-install-e5yONc/cffi/
  ----------------------------------------
ERROR: Command "/opt/dxc/python/bin/python2.7 /opt/dxc/python/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-OuvkVZ/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.8,!=1.11.3; python_implementation != '"'"'PyPy'"'"''" failed with error code 1 in None

Also tried installing binaries for AIX - ncpa-2.1.6.aix7.1.ppc.rpm, but ncpa_listener is always in inoperative state. ncpa_passive starts though.

Can you please provide any clues?

**Comment by jomann09** [comment] 2019-06-03 17:26
It's incredibly hard to build NCPA on AIX, is there a reason the currently available 2.1.6 version doesn't work for you?

**Comment by ahmedaijaz1** [comment] 2019-06-04 10:01
I had initially tried installing ncpa-2.1.6.aix7.1.ppc.rpm. The ncpa_listener service failed to restart without any error logged.
Updated openssl.base file-set to v1.0.2.1500 and re-installed ncpa-2.1.6.aix7.1.ppc.rpm. The service looks stable so far. Will observe this for a few days before we close this issue.

**Comment by jomann09** [comment] 2019-06-04 15:59
That sounds right, the openssl that comes is pretty outdated, I'm still working on perfecting the 2.1.7 built since the issue is that ncpa is not finding the proper libssl library so it uses the one that is installed on the system. That should be fixed in newer versions where it'll use the updated one that comes with it.

**Comment by ahmedaijaz1** [comment] 2019-06-05 11:16
Thanks Jake. That would be great. When are you planning to release v2.1.7?

**Comment by jomann09** [comment] 2019-06-13 21:47
Okay I think that the new one is working, just a bit more testing and I will release it fully tomorrow, if you'd like to try it out in the meantime here is the rpm: https://assets.nagios.com/downloads/ncpa/dev/

**Closed by jomann09** 2019-06-13 21:47 UTC

**Comment by ahmedaijaz1** [comment] 2019-06-17 12:19
#######################

$ oslevel -r
7200-03

#######################

$ lslpp -l | grep -i ssl
  openssl.base            1.0.2.1500  COMMITTED  Open Secure Socket Layer
  openssl.man.en_US       1.0.2.1500  COMMITTED  Open Secure Socket Layer
  openssl.base            1.0.2.1500  COMMITTED  Open Secure Socket Layer

#######################

$ rpm -qa | grep -i ncpa
ncpa-2.1.7-1.ppc

#######################

$ ./ncpa_listener
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-aix-7.1.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 11, in <module>
  File "/tmp/test/ncpa/agent/listener/certificate.py", line 2, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 12, in <module>
  File "ExtensionLoader_cryptography_hazmat_bindings__openssl.py", line 25, in <module>
  File "ExtensionLoader_cryptography_hazmat_bindings__openssl.py", line 17, in __bootstrap__
ImportError: Could not load module /usr/local/ncpa/cryptography.hazmat.bindings._openssl.so.
        Dependent module libssl.so could not be loaded.
Could not load module libssl.so.
System error: No such file or directory
Could not load module /usr/local/ncpa/cryptography.hazmat.bindings._openssl.so.
        Dependent module /usr/local/ncpa/cryptography.hazmat.bindings._openssl.so could not be loaded.

#######################

$ ldd /usr/local/ncpa/cryptography.hazmat.bindings._openssl.so
/usr/local/ncpa/cryptography.hazmat.bindings._openssl.so needs:
Cannot find libssl.so
Cannot find libcrypto.so
         /usr/lib/threads/libc.a(shr.o)
         /usr/lib/librtl.a(shr.o)
         /unix
         /usr/lib/libcrypt.a(shr.o)

#######################

$ find / -name 'libssl*' -print
/usr/lib/libssl.a
/usr/lib/libssl3.a
/usr/lib/libssl3.so
/usr/lib/libssl_compat.a
/usr/local/ncpa/libssl.a

#######################

$ ldd /usr/lib/libssl3.so
/usr/lib/libssl3.so needs:
         /usr/lib/libc.a(shr.o)
         /opt/freeware/lib/libnss3.so
         /opt/freeware/lib/libnssutil3.so
         /opt/freeware/lib/libplc4.so
         /opt/freeware/lib/libplds4.so
         /opt/freeware/lib/libnspr4.so
         /unix
         /usr/lib/libcrypt.a(shr.o)
         /usr/lib/libpthreads.a(shr_xpg5.o)
         /usr/lib/libodm.a(shr.o)
         /usr/lib/libcfg.a(shr.o)
         /usr/lib/libpthreads.a(shr_comm.o)

#######################

**Comment by jomann09** [comment] 2019-06-17 12:44
It looks like on the build server it was built against `openssl.base 1.0.2.1601` which might explain the discrepancy. If you run it using `LIBPATH=/usr/local/ncpa ./ncpa_listener` does it work?

**Comment by jomann09** [comment] 2019-06-17 13:00
Please try this build with the included .so files https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.1.7-2.aix7.1.ppc.rpm

**Comment by ahmedaijaz1** [comment] 2019-06-17 13:39
No it doesn't :(

######################
$ LIBPATH=/usr/local/ncpa; export LIBPATH
######################
$ echo $LIBPATH
/usr/local/ncpa
######################
$ cd /usr/local/ncpa
######################
$ ./ncpa_listener
Traceback (most recent call last):
  File "/opt/freeware/lib/python2.7/site-packages/cx_Freeze-4.3.4-py2.7-aix-7.1.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "ncpa_listener.py", line 11, in <module>
  File "/tmp/test/ncpa/agent/listener/certificate.py", line 2, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
  File "/opt/freeware/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 12, in <module>
  File "ExtensionLoader_cryptography_hazmat_bindings__openssl.py", line 25, in <module>
  File "ExtensionLoader_cryptography_hazmat_bindings__openssl.py", line 17, in __bootstrap__
ImportError: Could not load module /usr/local/ncpa/cryptography.hazmat.bindings._openssl.so.
        Dependent module libssl.so could not be loaded.
Could not load module libssl.so.
System error: No such file or directory
Could not load module /usr/local/ncpa/cryptography.hazmat.bindings._openssl.so.
        Dependent module /usr/local/ncpa/cryptography.hazmat.bindings._openssl.so could not be loaded.
######################

**Comment by ahmedaijaz1** [comment] 2019-06-17 13:44
Hmmm, https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.1.7-2.aix7.1.ppc.rpm looks good so far. Agents started fine

**Comment by jomann09** [comment] 2019-06-17 13:49
I believe the new build should fix things for you, let me know if there are any other issues!
