### ISSUE TITLE
Powershell script causing NCPA to crash

### ISSUE THREAD

**Issue by SuperGoodMike** [NagiosEnterprises/ncpa#145] opened 2015-02-06 18:39 UTC
Hello everyone,

I am currently working on a powershell script that is working great from the host. But every time I run it by calling it through NCPA It causes the NCPA service to become unresponsive. I need to restart the service to get it working again. Is anyone else have the same timeout issue? I am using the PSSnapin Microsoft.Exchange.Management.PowerShell.E2010. 

I had to change from powershell 32 to powershell 64 in order to use  PSSnapin Microsoft.Exchange.Management.PowerShell.E2010. I did this by changing the "Plugin directives"  in C:\Program Files (x86)\Nagios\NCPA\etc\ncpa.cfg 
from
.ps1=powershell.exe -ExecutionPolicy Unrestricted -File $plugin_name $plugin_args

to 

.ps1=C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Unrestricted -File $plugin_name $plugin_args

Any thoughts or help?

**Comment by scot0357** [comment] 2015-02-08 11:36
I bet this is caused by the timeout issue (as you had described.) I had not monkey patched shell calls which was causing the system to hang on very long running shell calls. This has been fixed in the soon to be released 1.8.0, which should be coming out shortly. I'd bet this is causing this issue.

**Comment by jhomann** [comment] 2016-05-10 05:42
Closing this since @scot0357 mentioned it was fixed for 1.8.0 and we haven't heard back. If it's still an issue, open a new ticket and we can look into this further.

**Closed by jhomann** 2016-05-10 05:42 UTC

**Comment by SuperGoodMike** [comment] 2016-05-10 13:14
Still issue ?

Sent from my iPhone

On May 10, 2016, at 1:42 AM, Jake Omann <notifications@github.com<mailto:notifications@github.com>> wrote:


Closing this since @scot0357<https://github.com/scot0357> mentioned it was fixed for 1.8.0 and we haven't heard back. If it's still an issue, open a new ticket and we can look into this further.

-
