### ISSUE TITLE
AIX ncpa crash but restore by itself

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#373] opened 2017-08-24 17:21 UTC
I query a ncpa agent to get json api detail
```
2017-08-24 13:16:03,418 21430858 INFO OURIP - - [2017-08-24 13:16:03] "GET /api?token=MYTOKEN HTTP/1.1" 301 582 0.003053
```
NCPA stop responding for a minute and I see that in the log.
```
2017-08-24 13:16:04,001 21430858 ERROR __new__() takes exactly 6 arguments (5 given)
Traceback (most recent call last):
  File "/tmp/test/ncpa/agent/listener/nodes.py", line 64, in walk
  File "/tmp/test/ncpa/agent/listener/nodes.py", line 148, in walk
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 176, in <lambda>
  File "/tmp/test/psutil/psutil/__init__.py", line 2347, in users
  File "/tmp/test/psutil/psutil/_psaix.py", line 167, in users
TypeError: __new__() takes exactly 6 arguments (5 given)
2017-08-24 13:16:04,003 21430858 ERROR __new__() takes exactly 6 arguments (5 given)
Traceback (most recent call last):
  File "/tmp/test/ncpa/agent/listener/nodes.py", line 64, in walk
  File "/tmp/test/ncpa/agent/listener/nodes.py", line 148, in walk
  File "/tmp/test/ncpa/agent/listener/psapi.py", line 177, in <lambda>
  File "/tmp/test/psutil/psutil/__init__.py", line 2347, in users
  File "/tmp/test/psutil/psutil/_psaix.py", line 167, in users
TypeError: __new__() takes exactly 6 arguments (5 given)
```

**Comment by jomann09** [comment] 2017-08-25 18:22
Closing this as a duplicate of #370 
I think it's only an issue with AIX as far as I know (just tested it) but I will get it fixed for the next build... something in AIX doesn't work right with the psutils common functions.

**Closed by jomann09** 2017-08-25 18:22 UTC
