### ISSUE TITLE
Logical Disk Memory not returning proper alert state

### ISSUE THREAD

**Issue by krobertson71** [NagiosEnterprises/ncpa#139] opened 2015-01-28 12:42 UTC
I am trying to alert on free space available on a certain logical partition.  Here is the api results I am working off of:

{
  "value": {
    "|var": {
      "total_size": [
        1040080896, 
        "b"
      ], 
      "used_percent": [
        17.8, 
        "%"
      ], 
      "used": [
        185470976, 
        "b"
      ], 
      "free": [
        800923648, 
        "b"
      ], 
      "device_name": [
        [
          "/dev/mapper/vg-var"
        ], 
        "name"
      ]
    }
  }
}

Now I enter this URL:

https://emovasd01:5693/api/disk/logical/|var/free?warning=900000000&critical=700000000&check=true

But I am getting this result:

{
  "value": {
    "returncode": 2, 
    "stdout": "CRITICAL: free was 800923648b | 'free_0'=800923648b;900000000;700000000;"
  }
}

It should be returning WARNING not CRITICAL.  Free space goes down as more is used.  I am trying to alert based on actual free space versus a percentage.  Certain people want a specific value to be alerted on.  This seems easy enough, but this looks to be using the greater than approach.

It's above the 700000000 critical threshold but below the warning threshold so it should read WARNING.

Any ideas?

**Comment by krobertson71** [comment] 2015-01-28 14:53
Changing it to used works fine.  Just subtract the number from the total they are asking for.  However when I try to put this in Nagios and test the check I get this:

COMMAND: /usr/local/nagios/libexec/check_ncpa.py -H emovasp01 -t 'mytoken' -P 5693 -M 'disk/logical/\|var/used' -w 170000000 -c 190000000
OUTPUT: Unable to run check on non-child node. Revise your query.

That is the same command that was there before, I just changed used_percentage and made it used and set the -w and -c to match the byte format the check is using by default.

Lost.

**Comment by jhomann** [comment] 2016-05-29 00:29
Need to verify if this fits with the Nagios Plugins guidelines for warning and critical values. My guess is that it does now, which would mean we would have to take a look at how NCPA is calculating those and possibly change them a bit. I will take a look at this and see what we can do.

**Comment by jomann09** [comment] 2016-08-13 08:02
Closing this due to it working as intended. Based on this documentation: https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

You need to use the `:` symbol after your values to get it to work the way you want.

So you should do `-w 12: -c 9:` to get your intended results. Remember if it makes it easier to understand while writing use the `-u G` or something to make it easier to read!

**Closed by jomann09** 2016-08-13 08:02 UTC
Labels: Question / Support
