### ISSUE TITLE
Nagios UNKNOWN	: CHECK_MEMORY_WINDOWS 

### ISSUE THREAD

**Issue by youcefsat87** [NagiosEnterprises/ncpa#733] opened 2021-01-08 09:14 UTC
Hello every body,

* I have this alarme in my Nagios server : 

**CHECK_MEMORY_WINDOWS** status : **UNKNOWN**: **An error occured connecting to API. (HTTP error: '500 INTERNAL SERVER ERROR')**

* In my remot machine in the log file of ncpalistener.log i have this logs : 

2020-12-30 06:54:13,219:ERROR:app:Exception on /api/memory/virtual/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 185, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 946, in api
  File "C:\ncpa\agent\listener\nodes.py", line 114, in run_check
  File "C:\ncpa\agent\listener\nodes.py", line 334, in run_check
UnboundLocalError: local variable 'perfdata' referenced before assignment

all others services work well : 

CHECK_DISK_WINDOWS    status OK

CHECK_PROCESS_WINDOWS    status OK

GENERIC_PING | GENERIC_PING    status OK

Can someone help ?

Thanks for all !

**Comment by jomann09** [comment] 2021-02-08 18:37
I'm not actually sure what the issue is, but it looks like the issue you're showing is actually separate. Normally, when there is an error it'll still run the check and give the error. Due to the perfdata not being set, it's erroring completely. I've made a fix for this so that it won't give a 500 error. However, you'll have to check your log file and see what the exception was before the UnboundLocalError exception to see the actual issue.

**Comment by jomann09** [comment] 2021-02-08 18:39
Here's the commit that fixes the above error 3bfc1f51f54ef1012d8e12ca18a13c5e19c12bdf, just note it doesn't actually make the check run it just stops the 500 error. Need more information for the check not running.

**Closed** 2021-02-08 22:26 UTC
Labels: Bug, Question
