### ISSUE TITLE
[NCPA 1.8.1] Linux listener crash that leaves behind a PID file won't gracefully restart

### ISSUE THREAD

**Issue by jm-welch** [NagiosEnterprises/ncpa#297] opened 2017-01-10 18:35 UTC
## Environment
RHEL 6.8
NCPA 1.8.1

## Issue Description
I have not tested this with NCPA 2.0 yet - should be able to do that some time today. If it's fixed in 2, I'll close this request out.

* NCPA Listener crashes, leaving behind its PID file. 
* `service ncpa_listener status` shows that the service is running, but a quick check on ps shows that it isn't. 
* `service ncpa_listener restart` looks like it restarts, but in fact, it doesn't, due to the existing pid file

``` shell
# service ncpa_listener status
Process running with PID 1615

# ps -fp 1615
UID        PID  PPID  C STIME TTY          TIME CMD

# service ncpa_listener restart
pid 1615 did not die
Exited.
another instance seems to be running (pid 1615), exiting
Started listener...

# service ncpa_listener status
Process running with PID 1615

# ps -fp 1615
UID        PID  PPID  C STIME TTY          TIME CMD
```

## Steps to reproduce
1. Start the service
2. Run `service ncpa_listener status` to identify the pid
3. Run `kill -9 <pid>` to kill it
4. Run `ps -fp <pid>` to confirm that the service is dead
5. Check the service status via `service ncpa_listener status`

## Workaround
Once the pid file is removed, the service will start up normally.

## Desired fix
The service control script should:
* Check to ensure that the pid listed in the pid file is actually running NCPA before reporting that the service is up
* If the service is dead, but the pid file still exists, the script should remove the pid file and perform a fresh start

**Comment by jomann09** [comment] 2017-01-10 19:02
This has not been fixed in NCPA 2, it will have about the same effect if it dies without the pid being removed. At least I believe so... will have to double check the code and test it out.

**Comment by jomann09** [comment] 2017-01-16 14:31
Okay... this should result in no output in NCPA 2 however... I am not sure why it's not exiting properly ... or why the output doesn't say what it is supposed to! I will look into this more however, restarting the service in NCPA 2 does remove the old .pid file, and starts a new daemon (same with start) so that issue is fixed.

**Comment by jomann09** [comment] 2017-01-19 09:19
Fixed this better in 0c154e5 for 2.0.2

**Closed by jomann09** 2017-01-19 09:19 UTC
Labels: Bug

**Comment by DITLPANW** [comment] 2018-01-28 07:52
@jomann09  Hi there,
I just looking on this issue and I have a similar problem in all of macOS version with NCPA 2.1.1.
It's look like on start up the daemon entered into a state of race on a resource with kernal services.
To me it happens mainly in NCPA listener.
Threre are some fixed for this issue? 
Tahnks,

**Comment by jomann09** [comment] 2018-01-29 04:38
I have not heard of it happening on macOS, can you explain a little bit about what is happening. If you can see anything that is causing it, and possibly if there is anything off in the ncpa_listener.log file?

**Comment by DITLPANW** [comment] 2018-01-29 10:25
Sure, 
After the installation its work well and after a few restart, the problems begin.
You can see the listener log file:
![image](https://user-images.githubusercontent.com/29203401/35504856-e0b0a692-04ec-11e8-9d72-9883f539e05e.png)

The problem starts after the restart when the daemon tries to start, see the daemon status, there is a status 1 but there is no PID : 
![image](https://user-images.githubusercontent.com/29203401/35505488-ecec47de-04ee-11e8-9455-23a89edd53b7.png)

And when I tried to run "NCPA_listner" manually, I get the following error: 
![image](https://user-images.githubusercontent.com/29203401/35505624-53831d88-04ef-11e8-8647-789c5859462a.png)

Tell me if do you need something else?

**Comment by DITLPANW** [comment] 2018-01-29 10:35
Ohh... 
And PID 90 : 
![image](https://user-images.githubusercontent.com/29203401/35506106-e735d010-04f0-11e8-9360-a0f3e733f682.png)

**Comment by jomann09** [comment] 2018-01-31 18:59
Is there anything in the `/usr/local/ncpa/var/` directory like lock files or anything that didn't get cleared?

**Comment by DITLPANW** [comment] 2018-02-01 12:46
![image](https://user-images.githubusercontent.com/29203401/35679146-ae3d2806-075e-11e8-8e71-0308b8570921.png)

**Comment by jomann09** [comment] 2018-02-01 20:51
Huh that is interesting, what version of macOS are you running? I will test this tomorrow on a couple macs and see if I can get it to do the same - when I tested 2.1.1 it wasn't causing issues but I don't think I restarted the system.

**Comment by DITLPANW** [comment] 2018-02-03 16:38
This behaviour was reproduced on all of the following list (VM with Latest version):
10.11.
10.12.
10.13.
After the installation, It should work well.
Try to restart the system even a few times.
Let me know if I can help

**Comment by jomann09** [comment] 2018-02-07 18:07
So I just tried this in 10.13 (Laptop) and 10.12 (VM) a few different ways and still am not seeing this happening... the not loading on startup. Can you check the system log for NCPA references?
Using something like `cat /var/log/system.log | grep ncpa` ? Does it do this every time you restart?

**Comment by DITLPANW** [comment] 2018-02-11 11:36
![image](https://user-images.githubusercontent.com/29203401/36072891-38402304-0f30-11e8-845b-4564d6d9596e.png)
------------------------------
![image](https://user-images.githubusercontent.com/29203401/36072912-5c7088f4-0f30-11e8-93cb-c0fca5247cb4.png)
-------------------------------
Yes, every restart...

**Comment by jomann09** [comment] 2018-02-20 14:25
I'd definitely remove the .pid files if the services have exited, because they won't overwrite them - and in that case will never start up.

**Comment by cyrilstoll** [comment] 2024-03-05 08:25
Why not put the PID file into a tmpfs directory like /run as almost every other software does? All the tmpfs directories get their content deleted by a reboot as it's in RAM rather than on disk. This way you don't need to implement a logic to delete the PID file as that is taken care of automatically in case of a reboot.
