### ISSUE TITLE
ncpa 2.2.0 on Ubuntu 18.04 won't start

### ISSUE THREAD

**Issue by micoots** [NagiosEnterprises/ncpa#589] opened 2019-10-28 01:45 UTC
Hi,

2.1.9 was running fine, auto-upgrade occurred last night to 2.2.0 and now it's broken:

tail -20 /usr/local/ncpa/var/log/ncpa_passive.log
  File "ncpa_passive.py", line 93, in <module>
  File "/root/ncpa/agent/ncpadaemon.py", line 80, in main
  File "/root/ncpa/agent/ncpadaemon.py", line 185, in start
  File "/root/ncpa/agent/ncpadaemon.py", line 66, in setup_user
  File "/root/ncpa/agent/listener/database.py", line 41, in setup
OperationalError: attempt to write a readonly database

and we see:

ll /usr/local/ncpa/var/ncpa.db
-rw-rw-r-- 1 root root 0 Oct 24 15:53 /usr/local/ncpa/var/ncpa.db

chgrp nagios /usr/local/ncpa/var/ncpa.db

Then restarted, both daemons restarted correctly.

I thought we had this ncpa.db issue fixed since the last time this happened on the 2.1.9 upgrade?

Michael.

**Comment by jomann09** [comment] 2019-10-28 14:04
Let me check a few things, I don't think it's supposed to update that file. It shouldn't be writing out an empty one as root:root.

**Comment by jomann09** [comment] 2019-10-28 18:54
I just tested this again, the file defaults to root:nagios and is writeable. The only actual bug that I see is that it should not be overwriting the database with the new empty one if there is one that already exists. That should be fixed in the next version. For your issue specifically, I'm not sure why yours is setting it to root:root on upgrade.

**Comment by jomann09** [comment] 2020-02-20 20:14
Okay finished testing this, the issue is going to be resolved after you're on 2.2.1+ so on the 2.2.1 upgrade it will remove your ncpa.db and replace it with an empty one.

**Closed by jomann09** 2020-02-20 20:14 UTC
Labels: Bug
