### ISSUE TITLE
Incorrect status of service vmware-tools

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#170] opened 2015-04-15 06:11 UTC
The API shows a wrong status of vmware-tools service.

/api/service/vmware-tools?check=true&status=running:
```json
{
  "value": {
    "returncode": 2, 
    "stdout": "CRITICAL: Service vmware-tools is stopped"
  }
}
```

```
[root@localhost ~]# service vmware-tools status
vmtoolsd is running
```

**Comment by ccztux** [comment] 2015-04-15 06:13
Please let me know, if i can provide some usefull informations.

**Comment by varnar** [comment] 2015-04-15 11:05
@ccztux 
This has been already reported in https://github.com/NagiosEnterprises/ncpa/issues/142
But developers has not fixed yet it.

The issue is that the NCPA trying to find running service based on the provided name in processes, not using service <name> status.

There should be clear view of running process and running service.

**Comment by jm-welch** [comment] 2015-04-15 17:28
Some other discussion around this issue (and a workaround using processes) in #137

**Comment by jhomann** [comment] 2016-05-11 04:00
Closing this as duplicate. Working on issue though via other issue tickets.

**Closed by jhomann** 2016-05-11 04:00 UTC
