### ISSUE TITLE
NCPA runs as root instead of nagios

### ISSUE THREAD

**Issue by ludmilmm** [NagiosEnterprises/ncpa#181] opened 2015-06-17 16:21 UTC
According to the ncpa.cfg, ncpa should run as "nagios" user...
```
[listener]
uid = nagios
...
```
but instead it runs as root.
```
# ps -ef | grep [n]cpa
root      3261     1  0 11:17 ?        00:00:00 /usr/local/ncpa/ncpa_posix_passive start
root      3270     1  0 11:18 ?        00:00:00 /usr/local/ncpa/ncpa_posix_listener start
```
You can start the ncpa_posix_listener and the ncpa_posix_passive as "nagios" user:
```
# /usr/local/ncpa/ncpa_posix_listener --stop
# /usr/local/ncpa/ncpa_posix_passive --stop
# su - nagios
$ /usr/local/ncpa/ncpa_posix_listener --start
$ /usr/local/ncpa/ncpa_posix_passive --start
$ ps -ef | grep [n]cpa
nagios    1325     1  0 11:11 ?        00:00:00 /usr/local/ncpa/ncpa_posix_listener --start
nagios    1379     1  0 11:11 ?        00:00:00 /usr/local/ncpa/ncpa_posix_passive --start
```
however, this leads to a couple of issues:

First. You can no longer access the API from the web UI
```
https://ipaddress:5693/api
```
Second. Checks no longer work
```
/usr/local/nagios/libexec/check_ncpa.py -H <client ip> -t 'mytoken' -P 5693 -M cpu/percent -w 20 -c 40
UNKNOWN: Error occurred while running the plugin. Use the verbose flag for more details.
```

**Comment by jhomann** [comment] 2015-10-26 17:33
Assigning this to Nick to see if he has more information for us about how NCPA is supposed to run. My understanding is that the passive checks are ran by the nagios user and all checks themselves that get ran via the API are ran by nagios but the actual listener/passive agent must be ran as root/system (windows) to get a lot of the server status information.

**Comment by daVikes** [comment] 2015-10-26 17:55
I have set those as well and the processes are running as root.  The log files seem to be created as nagios:nagcmd however except for pid files.   So perhaps its more about file permissions?

**Comment by jhomann** [comment] 2016-05-09 23:31
I'm pretty sure that it needs to run as root to get escalated permissions for certain things but when it actually runs it's running as nagios not root.

**Closed** 2016-05-09 23:33 UTC
Labels: question

**Comment by ericloyd** [comment] 2016-09-14 19:50
Can we open this back up?  This is a show-stopper for some of our clients who are not allowed to run root-based software on their customers' machines that they're monitoring.  Yet, NCPA is supposed to be the wave of the future.  

I can't understand why, if it's so great, there's very little active development?

**Comment by krobertson71** [comment] 2016-09-14 20:11
I feel your pain Eric.  That has become a growing topic here at Duke as well.

The problem is.. Other monitoring solutions provide the ability to execute certain agent queries using SUDO in an linux environment.  NCPA runs as root, not the nagios user, when installed.  We have tried in the past to work around this without a satisfactory solution.

I also agree with your NCPA development concerns.  This was introduced when I attended the NagiosCon in 2014 and sold as the Universal agent and methodology going forward.  The development discussions I have seen lead me to believe there is not a lot of resources dedicated to this solution any longer.


On Sep 14, 2016, at 3:50 PM, Eric Loyd <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we open this back up? This is a show-stopper for some of our clients who are not allowed to run root-based software on their customers' machines that they're monitoring. Yet, NCPA is supposed to be the wave of the future.

I can't understand why, if it's so great, there's very little active development?

**Comment by jomann09** [comment] 2016-09-14 20:12
I've addressed this in another issue #252 here on GitHub. In 2.0.0 the actual daemon runs as root due to the daemon requiring root-only info and all plugins that it executes run as the user/group specified in the ncpa.cfg.

I mean I am all for running it as non-root... but how are you going to be monitoring data that only root has access to? At that point it seems like it's more worthwhile to use NRPE with only the plugins you know can work on that system. NCPA is not going to be the best agent for all situations. I'm not sure what would be sacrificed if we were running the daemon as a non-root user, it may be possible to allow it within the configuration file in the future.

Obviously that only works on Unix systems and on Windows it doesn't have a specific user that it runs as, besides system and you can set restrictions on the way powershell executes scripts.

**Comment by ericloyd** [comment] 2016-09-14 20:27
Jesse, that's my point.  It runs as root, but gathers information that is available through non-root utilities.  At least, the API does (for the most part).  uptime, free, df, /etc/proc, they all show things that are accessible to non-root users to a lesser or greater degree, and as Kris put it, this was "sold as the Universal agent and methodology going forward."  I think I first heard of its announcement at the 2013 conference when Nick Scott did a presentation about it.

Your point about run NRPE instead is spurious at best.  NRPE runs as the Nagios user, and if there are things that require root access, you can execute sudo.  NCPA is, at best, a "cute toy" in our eyes at this point, but not capable of being a true cross-platform replacement for anything. 

At the start of 2016, we started recommending to all our customers to make the switch to NCPA.  You keep saying things like "the intent" or something similar to "what someone thought when they programmed it."  Well, can't we say "we want it to run as the nagios user and execute plugins the same way NRPE does - via sudo, if we need them?"

We will need to start mea culpaing with our customers and say "sorry, what was supposed to be a great agent really isn't all that great, since it runs with elevated privs, can't be put into protected user space, and isn't being actively developed."

Kris, I feel your pain as well.

**Comment by jomann09** [comment] 2016-11-19 11:49
Just an update on this - having tested it as non-root (and fixing the setting of the uid and gid based on the section in the config) this is now default behavior in NCPA 2.0.

By default, both services will drop permissions during startup when it daemonizes itself and will run as **nagios:nagios** (or whatever you set in the config) - note that your plugins **will** run as the user that the process is running as - I commented out the code that changed the user before running checks.

I've tested it quite a bit on Linux... I will test it on Mac OS X next week and this is basically the last thing that needed to be fleshed out for 2.0 to be released.

**Comment by mkhammar** [comment] 2016-12-14 10:00
@jomann09 Hi, 

I have the same issue and in my environment I can't use the 2.0 version yet.

Is there any chance to get the same break fix in 1.8?

Thx

**Comment by jomann09** [comment] 2016-12-14 15:09
The fix will not be in a 1.8 version since it changed some ways the agent starts and honestly just not enough time to back-port fixes and rebuild. NCPA 2 is coming out tomorrow though.

**Comment by ericloyd** [comment] 2016-12-14 15:45
Oh yay!!  It will be out in time for me to play with it before Christmas!  Thanks!

**Comment by mkhammar** [comment] 2016-12-15 10:16
Thanks you, I will wait for the 2.0 deployment then.

Thx
