### ISSUE TITLE
Disk read_time and write_time

### ISSUE THREAD

**Issue by petrolej** [NagiosEnterprises/ncpa#630] opened 2020-05-07 08:23 UTC
Hi,

please what is the exact meaning of the

disk/physical/PhysicalDrive0/read_time and disk/physical/PhysicalDrive0/write_time ?

I cannot find any description for it.

Thanks.

**Comment by jomann09** [comment] 2020-06-03 20:27
Duplicate of answered issue #636

**Closed by jomann09** 2020-06-03 20:27 UTC
