### ISSUE TITLE
AIX Update from ncpa 2.0.4 to 2.0.5 failed

### ISSUE THREAD

**Issue by metabsd** [NagiosEnterprises/ncpa#379] opened 2017-09-07 16:59 UTC
Hi,

I try to update both AIX 6 and 7. I have to same result.  Process seem to be working but in fact no.
```
root@sxtgbd0311:/root# ps -ef | grep -i ncpa
  nagios 30736460  5111972   0 12:37:25      -  0:00 /usr/local/ncpa/ncpa_passive -n
  nagios 37748986  5111972   0 12:37:25      -  0:00 /usr/local/ncpa/ncpa_listener -n
```

Before the upgrade I have this in /etc/inittab

```
ncpa_listener:2:once:/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_listener >/dev/null 2>&1
ncpa_passive:2:once:/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_passive >/dev/null 2>&1
```
We need that if someone reboot the server.

I try the command after the update `/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_listener` and I have that result `0513-085 The ncpa_listener Subsystem is not on file.`

Can you help me to patch for the moment and fix that please. We wait about your update before continue the upgrade of NCPA on AIX.

Thank you!

**Comment by typer100** [comment] 2017-09-07 17:06
Yep. Same issue here. Inittab entries are gone and ncpa is not registered as a service. Not sure exactly what the final result was suppose to be.

**Comment by jomann09** [comment] 2017-09-07 17:16
Let me check the spec file, this might be related to the upgrade issues I had before.

**Comment by jomann09** [comment] 2017-09-07 17:19
The code to fix this is:
```
mkssys -s ncpa_listener -p /usr/local/ncpa/ncpa_listener -u 0 -S -n 15 -f 9 -a '-n' >/dev/null 2>&1
mkssys -s ncpa_passive -p /usr/local/ncpa/ncpa_passive -u 0 -S -n 15 -f 9 -a '-n' >/dev/null 2>&1
mkitab "ncpa_listener:2:once:/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_listener >/dev/null 2>&1"
mkitab "ncpa_passive:2:once:/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_passive >/dev/null 2>&1"
```

I see the issue that is happening and I will rebuild it now. It's the same problem I was dealing with on the other RPM where it runs the uninstall after the install and I currently have it running rmsys and rmitab.

I will rebuild it and update the version that is on the site. I'll update the ticket once that's done.

**Comment by jomann09** [comment] 2017-09-07 17:23
One more thing to note, when upgrading you can use `--noscripts` on the RPM to not run the uninstall scripts and install scripts (they shouldn't be necessary for this upgrade) since the 2.0.4 RPM's uninstall script will be ran after it's upgraded to 2.0.5 - this will happen on all 2.0.4 -> 2.0.5 even after I fix the RPM.

**Comment by metabsd** [comment] 2017-09-07 18:54
I apply the patch and restart ncpa with that command `/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_listener`

I see that in the log and nothing appear when I try to communicate with the API.
```
2017-09-07 14:34:42,192 27328758 INFO started
2017-09-07 14:34:42,193 27328758 INFO Using SSL version TLSv1_2
```
I try to communicate with the API of NCPA `https://servername:5693` I got `Secure Connection Failed`

I switch the loggin mode to debug.

```
# Listener logging file level, location, and the PID location^M
# Default: loglevel = info (debug, info, warning, error)^M
# Default: logfile = var/log/ncpa_listener.log^M
# Default: pidfile = var/run/ncpa_listener.pid (leave listener in pid file name)^M
#^M
loglevel = info^M
logfile = var/log/ncpa_listener.log^M
pidfile = var/run/ncpa_listener.pid^M
```
ncpa.cfg have windows caracter as end of line. *Wierd*

I try to communicate with the API of NCPA `https://servername:5693` I got `Secure Connection Failed` again and nothing more in the log.

Thank a lot :)

**Comment by jomann09** [comment] 2017-09-07 19:46
Hmm let me make sure the windows line endings are gone, they were replaced but maybe they got back in there... it shouldn't have replaced your ncpa.cfg though.

How are you doing the test for the API, from the command line?

**Comment by metabsd** [comment] 2017-09-07 20:05
All my Nagios check are unknown and I try to access `https://servername:5693`

**Comment by jomann09** [comment] 2017-09-07 21:48
Okay I have a workaround (I am working on fixing this particular issue in the new build of 2.0.5, but you'll still want to use `--noscripts` on the 2.0.4 -> 2.0.5 upgrade after the new build!)

1. Kill all the ncpa processes by checking `ps aux | grep ncpa`
2. Remove all PIDS
`rm -f /usr/local/ncpa/run/*`
3. Remove empty key and cert file
`rm -rf /usr/local/ncpa/var/ncpa.key /usr/local/ncpa/var/ncpa.crt`
4. Add services
```
mkssys -s ncpa_listener -p /usr/local/ncpa/ncpa_listener -u 0 -S -n 15 -f 9 -a '-n'
mkssys -s ncpa_passive -p /usr/local/ncpa/ncpa_passive -u 0 -S -n 15 -f 9 -a '-n'
```
5. Start services (if you want)
```
mkitab "ncpa_listener:2:once:/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_listener"
mkitab "ncpa_passive:2:once:/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_passive"
```
This should fix the system. It looks like the issue is due to the empty .key and .crt file ... both those files should not be upgraded with the RPM and are likely what is causing the problem. I'm testing upgrades now to make sure it doesn't try to in the future.

**Comment by metabsd** [comment] 2017-09-08 12:33
I confirm the certificate have 0 byte. 

```
-rw-r--r--    1 nagios   nagios            0 Sep  1 14:08 ncpa.crt
-rw-r--r--    1 nagios   nagios            0 Sep  1 14:08 ncpa.key
```

**Comment by metabsd** [comment] 2017-09-08 12:38
I apply your workaround and it's working fine. We decide to wait the new rpm file. We are using yum to deploy the new version of ncpa and we don't have the hability to use --noscript with yum.

Thank you!

**Comment by jomann09** [comment] 2017-09-08 17:47
Alright this is fixed in the latest build and has been uploaded.

**If you're upgrading from 2.0.4 you must do one of the following:**

1. Install using `rpm -U --noscripts`
or
2. Install using `yum` or `rpm -U` and then run the following:
```
mkssys -s ncpa_listener -p /usr/local/ncpa/ncpa_listener -u 0 -S -n 15 -f 9 -a '-n'
mkssys -s ncpa_passive -p /usr/local/ncpa/ncpa_passive -u 0 -S -n 15 -f 9 -a '-n'
mkitab "ncpa_listener:2:once:/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_listener"
mkitab "ncpa_passive:2:once:/usr/bin/startsrc -e LIBPATH=/usr/local/ncpa -s ncpa_passive"
```
_**You may need to kill the currently running NCPA processes like mentioned above, and restart them**_

I apologize for this happening. This is fairly new territory (rpm packaging) although this new rpm should work correctly once these minor issues are fixed.

_If you don't have any special configurations on the machines, you could also uninstall ncpa and install the new one. This would mean losing configuration but it would also mean that you're guaranteed not to hit the removed src problem._

**Comment by jomann09** [comment] 2017-09-10 03:07
Going to close this since the new rpm is out. Let me know if you have any more issues.

**Closed by jomann09** 2017-09-10 03:07 UTC
Labels: Priority
