### ISSUE TITLE
An error occurred:HTTP Error 500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by AlexSavVl** [NagiosEnterprises/ncpa#509] opened 2018-11-19 06:16 UTC
Hello!
received the error while using ncpa-2.1.6.exe on windows 2008R2
My in my case java.exe is running. java is absent. Services Netlogon is stopped and LanmanServer is running
```
$ /usr/local/nagios/libexec/check_ncpa.py -H x.x.x.x -v -t 'test_token' -P 5693 -M 'processes' -q 'name=java.exe' -w 1
Connecting to: https://x.x.x.x:5693/api/processes/token=test_token&warning=1&check=1&name=java.exe
An error occurred:HTTP Error 500: INTERNAL SERVER ERROR

```
```
$ /usr/local/nagios/libexec/check_ncpa.py -H x.x.x.x -t 'test_token' -P 5693 -M 'processes' -q 'name=java' -w 1
OK: Process count for processes named java was 0 | 'process_count'=0;1;;
```
```
$ /usr/local/nagios/libexec/check_ncpa.py -H x.x.x.x -t 'test_token' -P 5693 -M 'services' -q 'service=Netlogon,status=stopped'
OK: Netlogon is stopped
```
```
$ /usr/local/nagios/libexec/check_ncpa.py -H x.x.x.x -t 'test_token' -P 5693 -M 'services' -q 'service=LanmanServer,status=running'
OK: LanmanServer is running
```

`$ /usr/local/nagios/libexec/check_ncpa.py -H x.x.x.x -v -t my_token' -P 5693-M 'processes' --warning=100 --critical=200`

```
$ /usr/local/nagios/libexec/check_ncpa.py -H x.x.x.x -t 'test_token' -P 5693 -M 'system/version'
OK: Version was ['6.1.7601']
```

The problem was discussed here
https://support.nagios.com/forum/viewtopic.php?f=16&t=51177

**Comment by AlexSavVl** [comment] 2018-11-19 06:17
ncpa_listener.log from the client
```
2018-11-16 12:16:49,418:ERROR:app:Exception on /api/processes/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
  File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
  File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
  File "C:\ncpa\agent\listener\server.py", line 169, in token_auth_decoration
  File "C:\ncpa\agent\listener\server.py", line 927, in api
  File "C:\ncpa\agent\listener\processes.py", line 420, in run_check
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf1 in position 360: ordinal not in range(128)
```

**Comment by jomann09** [comment] 2018-11-30 17:37
Is there special characters (non ascii) in any of the data that is being passed back? Can you run `--list` with the plugin on the first one that is erroring?

**Comment by AlexSavVl** [comment] 2018-12-03 13:02
```
$ /usr/local/nagios/libexec/check_ncpa.py -H x.x.x.x -v -t 'test' -P 5693 --list
Connecting to: https://x.x.x.x:5693/api?token=test
An error occurred:HTTP Error 500: INTERNAL SERVER ERROR
```

We use windows with russian language

**Comment by AlexSavVl** [comment] 2018-12-06 08:09
The same problem with ncpa 2.1.1 and AIX 6.

From https client all works until I set "Run as a Nagios Ccheck". On both - windows and AIX

**Comment by AlexSavVl** [comment] 2018-12-07 06:32
Ok. Fix on Windows, please.

**Comment by jomann09** [comment] 2019-05-02 20:35
Closing this as duplicate of #439 will track it there

**Closed by jomann09** 2019-05-02 20:35 UTC
Labels: Bug, Duplicate
