### ISSUE TITLE
Interface - bytes recd/sent not accurate

### ISSUE THREAD

**Issue by celticguy42** [NagiosEnterprises/ncpa#191] opened 2015-09-08 20:26 UTC
Using agent 1.8.1

The API address /interface/Ethernet/bytes_recv (and bytes_sent) does not appear to accurately pull data when the amount the value has changes is >4Gb on the server.  I'm assuming this is a 32bit variable.

For example, get-netadapterstatistics (powershell) shows 42,215,651,613 bytes received, but the API returns 4,168,549,886 (there is about 10 seconds difference in when these numbers were read).

Is there a workaround?

**Comment by jhomann** [comment] 2015-10-26 17:31
This may be able to be fixed with a 54bit version but I am not sure - we will have to check out psutil and verify that this will work... or find a workaround.

**Comment by jhomann** [comment] 2016-05-08 06:35
Tested this on the 64 bit version of python and 32 bit version and still seem to have the same type of issue. I am asking the psutil dev to see if it's a problem with how the data is retrieved from windows.

**Comment by jhomann** [comment] 2016-05-23 05:04
Asked about this issue with **psutil** which is by I set it to pending request:
https://github.com/giampaolo/psutil/issues/816

**Comment by jhomann** [comment] 2016-06-07 08:22
I've updated the psutil bug since it looks like I see why the problem is occurring. Looking into a solution to this, hopefully we will see Giampaolo look into it too.

**Comment by jhomann** [comment] 2016-06-10 07:46
Another update on this. The issue has been fixed although we are working on whether or not we need to adjust it for Win XP.

**Comment by jhomann** [comment] 2016-06-10 18:01
This will be fixed in 2.0.0 the build server for windows versions of NCPA already has the fixes for psutil in it and the latest builds work.

**Closed by jhomann** 2016-06-10 18:01 UTC
Labels: Bug, Pending Requirement
