### ISSUE TITLE
ncpa_listener.service exists with python error on fresh install of Ubuntu 22.04 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by murdock-illinois** [NagiosEnterprises/ncpa#871] opened 2022-05-23 21:53 UTC
Followed instructions in BUILDING.rst; build and install worked fine but it won't run -- exits immediately with python error about FIPS_mode being undefined:

ncpa_listener.service - LSB: This manages the NCPA Listener service
     Loaded: loaded (/etc/init.d/ncpa_listener; generated)
     Active: active (exited) since Mon 2022-05-23 14:41:15 MST; 47s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 3189 ExecStart=/etc/init.d/ncpa_listener start (code=exited, status=0/SUCCESS)
        CPU: 165ms

May 23 14:41:15 newcomp ncpa_listener[3191]:   File "/usr/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 17, in <module>
May 23 14:41:15 newcomp ncpa_listener[3191]:     from OpenSSL._util import (
May 23 14:41:15 newcomp ncpa_listener[3191]:   File "/usr/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
May 23 14:41:15 newcomp ncpa_listener[3191]:     from cryptography.hazmat.bindings.openssl.binding import Binding
May 23 14:41:15 newcomp ncpa_listener[3191]:   File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
May 23 14:41:15 newcomp ncpa_listener[3191]:     from cryptography.hazmat.bindings._openssl import ffi, lib
May 23 14:41:15 newcomp ncpa_listener[3191]:   File "ExtensionLoader_cryptography_hazmat_bindings__openssl.py", line 25, in <module>
May 23 14:41:15 newcomp ncpa_listener[3191]:   File "ExtensionLoader_cryptography_hazmat_bindings__openssl.py", line 17, in __bootstrap__
May 23 14:41:15 newcomp ncpa_listener[3191]: ImportError: /usr/local/ncpa/cryptography.hazmat.bindings._openssl.so: undefined symbol: FIPS_mode
May 23 14:41:15 newcomp systemd[1]: Started LSB: This manages the NCPA Listener service.

...any ideas or suggestions about what is going on, how to work around it?

Rob

**Comment by jomann09** [comment] 2022-05-27 21:49
I'm not sure if there's a good workaround, without doing some changes to the underlying packages and/or code. We will be working on a Ubuntu 22 build for NCPA 3 which we are working on the build process for now.

**Comment by austinjhunt** [comment] 2022-08-04 15:17
Hi @jomann09! Is there an estimated timeline for a new 22.04-friendly version of NCPA? We're about to begin rolling out the new OS within our infrastructure and we use NCPA heavily for monitoring so our goal is to include its installation in the provisioning template. Love the project!

**Comment by jomann09** [comment] 2022-08-29 19:11
I think this should work, you can test it out if you'd like - I'm still testing it but unless I find anything major this should be out here in the next few days. https://assets.nagios.com/downloads/ncpa/dev/ncpa-2.4.0.u22.amd64.deb

**Comment by jomann09** [comment] 2022-08-29 19:27
Closing this as a duplicate of #868 though, will track any more changes there.

**Closed by jomann09** 2022-08-29 19:27 UTC
Labels: Bug
