### ISSUE TITLE
Windows server with 21 drives (NCPA only displays 10)

### ISSUE THREAD

**Issue by chr00ted** [NagiosEnterprises/ncpa#863] opened 2022-04-04 19:21 UTC
Hello, I'm using NCPA 2.40 for WIn. I have 21 drives (not counting the CD/DVD) drive.  Drives C is physical, the other drives are LUNS from a SAN (These are all formatted NTFS). Anyway, when I go to https://localhost:5693 and goto "Live Data" and Disks, I only see 10 of the 21 drives showing. In Windows explorer, I can see and access all the drives. in the ncpa.cfg, I have the default of all_partitions=1. 

Please let me know if you need any other info from me.

**Comment by chr00ted** [comment] 2022-04-04 19:28
The disks are shown in diskmgmt.msc as well

**Comment by chr00ted** [comment] 2022-04-04 19:58
![WTF](https://user-images.githubusercontent.com/22943838/161622017-76d00908-e995-4e08-aead-bd18b38d823c.PNG)

**Comment by chr00ted** [comment] 2022-04-04 19:59
![image](https://user-images.githubusercontent.com/22943838/161622184-7f9a5764-4fe9-4756-a7b6-4abaf52790ba.png)

**Comment by MrPippin66** [comment] 2022-04-08 17:07
Can you show what is listed in /gui/api for the disk and logical view?

![image](https://user-images.githubusercontent.com/50372387/162489176-28a9e8b0-9727-4d75-a82e-ec16278c52d6.png)

**Comment by HunnyPuns** [comment] 2022-04-10 04:56
I was able to recreate this. Assuming I'm understanding the naming convention in chrooted's screenshots, I thought the core of the problem might've been NTFS mount points that have the same name, but on different drive letters. I spun up a VM with a few disks attached, confirmed I could see all of them if they were mounted via drive letters. Then left the E: and F: drives mounted, but mounted the remaining 2 disks as E:\DirName and F:\DirName. Sure 'nuff, NCPA only saw E:\DirName. Unmounting E:\DirName, and F:\DirName shows up in NCPA.

**Comment by MrPippin66** [comment] 2022-04-10 17:33
Okay. This may be due to https://github.com/giampaolo/psutil/pull/1961.

Code committer will need to validate.

**Comment by chr00ted** [comment] 2022-04-11 18:01
Thank you @HunnyPuns  & @MrPippin66

**Comment by chr00ted** [comment] 2022-04-11 18:07
> Can you show what is listed in /gui/api for the disk and logical view?
> 
> ![image](https://user-images.githubusercontent.com/50372387/162489176-28a9e8b0-9727-4d75-a82e-ec16278c52d6.png)

@MrPippin66 , Do you still need this or is @HunnyPuns confirmation suitable for you? If you would still like the screenshot, let me know and I'll gather it for you. I appreciate both of your help!

**Comment by ccztux** [comment] 2022-04-13 17:37
The fix https://github.com/giampaolo/psutil/pull/1961 was merged into release `5.9.0` of psutil. As described here https://github.com/NagiosEnterprises/ncpa/issues/844 ncpa was released a few days before. This means, that ncpa `2.4.0` was built with psutil `5.8.0` not including the fix.

**Comment by MrPippin66** [comment] 2022-04-13 17:49
That's what I thought. Any idea if they will release a new V2 release, or all future versions holding out for the V3 release?

**Comment by chr00ted** [comment] 2022-07-28 14:04
Just checking back in if there has been an updated on this (no rush...just checking in)

**Closed** 2024-04-03 12:33 UTC
