### ISSUE TITLE
Accented characters in URL result in error 500

### ISSUE THREAD

**Issue by Thibibi** [NagiosEnterprises/ncpa#499] opened 2018-10-29 10:43 UTC
Hi,

I'm building a plugin for which I send a full **path file name in parameter**. As soon as there is an accent or special character in the file name, NCPA ends with Internal Error 500. Seems like the plugin script does not even get launched, the error is before.

I tried with simple un-escaped **é** in the URL, then url-encoded ISO-8859-1 equivalent **%E9**, then also the url-encoded utf-8 equivalent **%C3%A9**

All resulted in Internal Error 500.

Example looking for file **D:\DPM\capé**: https://host:5693/api/plugins/check_ms_win_files.ps1?args=-F%20%27D:\DPM\cap%E9%27&args=-ane&args=-w%2020k&args=-c%205M

**Comment by jomann09** [comment] 2018-10-30 14:35
This has something to do with whatever the console is opened with, so it's likely that the plugin is giving a weird character to NCPA when it tries to parse the output from the console. I am still not 100% certain how to fix this, since it seems that python opens a console with an encoding that is supposed to be matching the system's base encoding, which is normally not UTF-8 on Windows. Is your system set to a specific encoding and language?

**Comment by Thibibi** [comment] 2018-10-30 15:32
No specific encoding or language. Windows Server 2012 R2, version 6.3 (Build 9600). Plugin is a ps1 script, directive is the default one:
powershell -ExecutionPolicy Bypass -File $plugin_name $plugin_args

**Comment by jomann09** [comment] 2019-05-02 20:36
Closing this as duplicate of #439 will track it there

**Closed by jomann09** 2019-05-02 20:36 UTC
Labels: Bug, Duplicate
