### ISSUE TITLE
API - disk/logical does not show reserved disks

### ISSUE THREAD

**Issue by ssaxnagios** [NagiosEnterprises/ncpa#231] opened 2016-06-07 22:01 UTC
Not sure if this is a bug or expected functionality, you can view them in powershell.

./check_ncpa.py -H X.X.X.X -t apipass -M 'disk/logical/' -l does not show reserved disks, see here:

https://support.nagios.com/forum/viewtopic.php?f=16&t=38618

**Comment by jhomann** [comment] 2016-06-08 00:21
Duplicate of https://github.com/NagiosEnterprises/ncpa/issues/102

**Closed by jhomann** 2016-06-08 00:21 UTC
